/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tethproj;

import UTIL.AESCrypt;
import UTIL.DBHelper;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SamaherD
 */
public class Add_Secertary extends javax.swing.JFrame {

    static String username;

    public Add_Secertary() {

        initComponents();
        setSize(511, 280);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newSecertaryPasswordText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newSecertaryNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        currentAdminPasswordText = new javax.swing.JPasswordField();
        addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        jPanel1.add(newSecertaryPasswordText);
        newSecertaryPasswordText.setBounds(170, 110, 200, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Secretary Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 70, 115, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Secretary Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 142, 17);
        jPanel1.add(newSecertaryNameText);
        newSecertaryNameText.setBounds(170, 70, 200, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("enter your passord:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 137, 20);

        currentAdminPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentAdminPasswordTextActionPerformed(evt);
            }
        });
        jPanel1.add(currentAdminPasswordText);
        currentAdminPasswordText.setBounds(170, 150, 200, 28);

        addbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn);
        addbtn.setBounds(200, 200, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 200, 80, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(70, 50, 370, 2);

        title.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        title.setText("Add New Secretary");
        title.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(title);
        title.setBounds(110, 0, 330, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/oral-health-care-technologies-510x245.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 510, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        String newSecertaryName = newSecertaryNameText.getText().trim();
        String newSecertaryPassword = newSecertaryPasswordText.getText().trim();
        String currentAdminPassword = currentAdminPasswordText.getText().trim();

        try {
            if (DBHelper.checkPassword(Login.getUserName(), AESCrypt.encrypt(currentAdminPassword))) { //Check if current admin password is correct
                if (DBHelper.isValidUserName(newSecertaryName)) {// Check if new secretay doesnt exists in database then it is valid name
                    if (DBHelper.addUser(2, newSecertaryName, AESCrypt.encrypt(newSecertaryPassword))) { // Add new secretary
                        JOptionPane.showMessageDialog(null, "Added Successfully");
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "This Secertary name is exist please try another name");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Your password is wrong!");
                currentAdminPasswordText.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(Add_Secertary.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void currentAdminPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentAdminPasswordTextActionPerformed

    }//GEN-LAST:event_currentAdminPasswordTextActionPerformed
    public static void setUser(String s) {
        username = s;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Secertary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Secertary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Secertary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Secertary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Secertary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JPasswordField currentAdminPasswordText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField newSecertaryNameText;
    private javax.swing.JPasswordField newSecertaryPasswordText;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
