package tethproj;

import UTIL.DBHelper;
import com.toedter.calendar.JDateChooser;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SamaherD
 */

public class AddPatient extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    //  DateFormat dateFormat = null;
    //  private SimpleDateFormat format;
    //  public static String d = null;
    public AddPatient() {
        //  jDateChooser.addPropertyChangeListener("date", new PropertyChangeListener() {
        //     @Override
        //     public void propertyChange(PropertyChangeEvent evt) {

        //  JDateChooser chooser = (JDateChooser)evt.getSource();
        // SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:MM:SS");
        //             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //      }
        //   });
        initComponents();
        jDateChooser.setDateFormatString("dd/MM/yyyy");
        Date date = new Date();
        jDateChooser.setDate(date);
        //  JOptionPane.showMessageDialog(null, username);
        //  dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //    Date date = new Date();
        //    d = dateFormat.format(date);
        //    txt_Data.setText(d);
        //   lbl_data.hide();

        //      format = ((JSpinner.DateEditor) Data_patient.getEditor()).getFormat();
        //  format.applyPattern("dd-MM-YYYY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Data_patient = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        txt_ln = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        txt_Ammount = new javax.swing.JTextField();
        txt_Paid = new javax.swing.JTextField();
        txt_Remain = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        t16 = new javax.swing.JCheckBox();
        t15 = new javax.swing.JCheckBox();
        t14 = new javax.swing.JCheckBox();
        t13 = new javax.swing.JCheckBox();
        t12 = new javax.swing.JCheckBox();
        t11 = new javax.swing.JCheckBox();
        t10 = new javax.swing.JCheckBox();
        t9 = new javax.swing.JCheckBox();
        t8 = new javax.swing.JCheckBox();
        t7 = new javax.swing.JCheckBox();
        t6 = new javax.swing.JCheckBox();
        t5 = new javax.swing.JCheckBox();
        t4 = new javax.swing.JCheckBox();
        t3 = new javax.swing.JCheckBox();
        t2 = new javax.swing.JCheckBox();
        t1 = new javax.swing.JCheckBox();
        t31 = new javax.swing.JCheckBox();
        t30 = new javax.swing.JCheckBox();
        t29 = new javax.swing.JCheckBox();
        t28 = new javax.swing.JCheckBox();
        t27 = new javax.swing.JCheckBox();
        t26 = new javax.swing.JCheckBox();
        t25 = new javax.swing.JCheckBox();
        t24 = new javax.swing.JCheckBox();
        t23 = new javax.swing.JCheckBox();
        t22 = new javax.swing.JCheckBox();
        t21 = new javax.swing.JCheckBox();
        t20 = new javax.swing.JCheckBox();
        t19 = new javax.swing.JCheckBox();
        t18 = new javax.swing.JCheckBox();
        t17 = new javax.swing.JCheckBox();
        t32 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Medication_txtArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Comment_TextArea = new javax.swing.JTextArea();
        B_add = new javax.swing.JButton();
        B_Clear = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        B_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Data_patient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Data_patient.setModel(new javax.swing.SpinnerDateModel());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("First name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 90, 20);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Last name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 60, 90, 20);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Address:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 100, 80, 20);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Phone :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 150, 50, 20);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setLabelFor(txt_Ammount);
        jLabel6.setText("Required Amount:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 20, 130, 20);

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("paid:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 60, 40, 20);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Remain:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 100, 60, 20);

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Date:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 140, 50, 30);

        txt_fn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fn);
        txt_fn.setBounds(130, 20, 180, 30);

        txt_ln.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txt_ln);
        txt_ln.setBounds(130, 60, 180, 30);

        txt_Address.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txt_Address);
        txt_Address.setBounds(130, 100, 180, 30);

        txt_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PhoneKeyReleased(evt);
            }
        });
        jPanel1.add(txt_Phone);
        txt_Phone.setBounds(130, 140, 180, 30);

        txt_Ammount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_AmmountKeyReleased(evt);
            }
        });
        jPanel1.add(txt_Ammount);
        txt_Ammount.setBounds(460, 20, 180, 30);

        txt_Paid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PaidKeyReleased(evt);
            }
        });
        jPanel1.add(txt_Paid);
        txt_Paid.setBounds(460, 60, 180, 30);

        txt_Remain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_RemainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_RemainMouseEntered(evt);
            }
        });
        jPanel1.add(txt_Remain);
        txt_Remain.setBounds(460, 100, 180, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Teeth"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });
        jPanel2.add(t16);
        t16.setBounds(40, 60, 21, 20);
        jPanel2.add(t15);
        t15.setBounds(80, 60, 20, 21);
        jPanel2.add(t14);
        t14.setBounds(120, 60, 20, 21);
        jPanel2.add(t13);
        t13.setBounds(160, 60, 20, 21);
        jPanel2.add(t12);
        t12.setBounds(210, 60, 20, 21);
        jPanel2.add(t11);
        t11.setBounds(250, 60, 20, 20);
        jPanel2.add(t10);
        t10.setBounds(290, 60, 21, 21);
        jPanel2.add(t9);
        t9.setBounds(330, 60, 20, 21);
        jPanel2.add(t8);
        t8.setBounds(370, 60, 21, 21);
        jPanel2.add(t7);
        t7.setBounds(410, 60, 20, 21);
        jPanel2.add(t6);
        t6.setBounds(460, 60, 20, 21);
        jPanel2.add(t5);
        t5.setBounds(500, 60, 20, 20);
        jPanel2.add(t4);
        t4.setBounds(540, 60, 20, 21);
        jPanel2.add(t3);
        t3.setBounds(580, 60, 20, 21);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel2.add(t2);
        t2.setBounds(620, 60, 20, 21);
        jPanel2.add(t1);
        t1.setBounds(660, 60, 20, 21);
        jPanel2.add(t31);
        t31.setBounds(80, 80, 20, 20);
        jPanel2.add(t30);
        t30.setBounds(120, 80, 21, 20);
        jPanel2.add(t29);
        t29.setBounds(160, 80, 21, 21);
        jPanel2.add(t28);
        t28.setBounds(210, 80, 20, 20);
        jPanel2.add(t27);
        t27.setBounds(250, 80, 21, 20);
        jPanel2.add(t26);
        t26.setBounds(290, 80, 21, 20);
        jPanel2.add(t25);
        t25.setBounds(330, 80, 20, 21);
        jPanel2.add(t24);
        t24.setBounds(370, 80, 21, 21);
        jPanel2.add(t23);
        t23.setBounds(410, 80, 20, 21);
        jPanel2.add(t22);
        t22.setBounds(460, 80, 20, 21);
        jPanel2.add(t21);
        t21.setBounds(500, 80, 20, 21);
        jPanel2.add(t20);
        t20.setBounds(540, 80, 20, 21);
        jPanel2.add(t19);
        t19.setBounds(580, 80, 21, 21);
        jPanel2.add(t18);
        t18.setBounds(620, 80, 20, 21);
        jPanel2.add(t17);
        t17.setBounds(660, 80, 20, 21);
        jPanel2.add(t32);
        t32.setBounds(40, 80, 20, 21);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/f.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 30, 666, 98);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 190, 720, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Medication"));
        jPanel3.setOpaque(false);

        Medication_txtArea.setColumns(20);
        Medication_txtArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Medication_txtArea.setRows(5);
        jScrollPane1.setViewportView(Medication_txtArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 340, 700, 130);

        jLabel10.setText("Comment:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 470, 110, 20);

        Comment_TextArea.setColumns(20);
        Comment_TextArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Comment_TextArea.setForeground(new java.awt.Color(204, 0, 0));
        Comment_TextArea.setRows(5);
        jScrollPane2.setViewportView(Comment_TextArea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 490, 690, 40);

        B_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_add.setText("Add");
        B_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_addActionPerformed(evt);
            }
        });
        jPanel1.add(B_add);
        B_add.setBounds(100, 543, 100, 30);

        B_Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_Clear.setText("Clear");
        B_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(B_Clear);
        B_Clear.setBounds(230, 543, 110, 30);
        jPanel1.add(jDateChooser);
        jDateChooser.setBounds(460, 140, 180, 30);

        B_exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B_exit.setText("Exit");
        B_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_exitActionPerformed(evt);
            }
        });
        jPanel1.add(B_exit);
        B_exit.setBounds(360, 543, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_edited.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 750, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t16ActionPerformed

    private void txt_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnActionPerformed

    private void B_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_addActionPerformed
        String patientName = txt_fn.getText().trim() + " " + txt_ln.getText().trim();
        String address = txt_Address.getText().trim();
        String phone = txt_Phone.getText().trim();
        int totalAmount = Integer.parseInt(txt_Ammount.getText().trim());
        int totalPaid = Integer.parseInt(txt_Paid.getText().trim());
        String addedBy = Login.getUserName();
        java.sql.Date sqlDate = new java.sql.Date(jDateChooser.getDate().getTime());
        String Medication = Medication_txtArea.getText().trim();
        String Comment = Comment_TextArea.getText().trim();
        int ammount = Integer.parseInt(txt_Ammount.getText().trim());
        int paid = Integer.parseInt(txt_Paid.getText().trim());
        String checkResult = "";

        JCheckBox CB[] = new JCheckBox[]{t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14,
            t15, t16, t17, t18, t19, t20, t21, t22, t23, t24, t25, t26, t27, t28, t29, t30, t31, t32};
        for (int i = 0; i < 32; i++) {
            if (CB[i].isSelected()) {
                checkResult += i + " ";
            }
        }

        if (isFillField()) { //check if all patient field is filled then add patient and visit
            try {
                int patientId = DBHelper.addPatients(patientName, address, phone, totalAmount, totalPaid, addedBy);
                if (patientId != 0) {
                    DBHelper.addVisit(sqlDate, patientId, Medication, Comment, ammount, paid, checkResult);
                    JOptionPane.showMessageDialog(null, "Added !");
                    
                     controlPanel c = new controlPanel();
                     c.show();
                     this.hide();
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Watch out! There's a missing Feild ! Fill all the feilds ", "Error  ", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_B_addActionPerformed

    private void B_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_exitActionPerformed
        // TODO add your handling code here:
        controlPanel c = new controlPanel();
        c.show();
        this.hide();

    }//GEN-LAST:event_B_exitActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void B_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ClearActionPerformed
        // TODO add your handling code here:
        JCheckBox CB2[] = new JCheckBox[]{t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22, t23, t24, t25, t26, t27, t28, t29, t30, t31, t32};

        txt_Address.setText("");
        txt_Ammount.setText("");
        txt_Paid.setText("");
        txt_Phone.setText("");
        txt_Remain.setText("");
        txt_fn.setText("");

        txt_ln.setText("");
        Comment_TextArea.setText("");
        Medication_txtArea.setText("");
        for (int i = 0; i < 32; i++) {
            CB2[i].setSelected(false);
        }
    }//GEN-LAST:event_B_ClearActionPerformed

    private void txt_RemainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_RemainMouseClicked
        // TODO add your handling code here:
        if (txt_Paid.getText().length() != 0 && txt_Ammount.getText().length() != 0) {
            int amm = Integer.parseInt(txt_Ammount.getText().trim());
            int pa = Integer.parseInt(txt_Paid.getText().trim());
            txt_Remain.setText(amm - pa + "");
        }
    }//GEN-LAST:event_txt_RemainMouseClicked

    private void txt_RemainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_RemainMouseEntered
        // TODO add your handling code here:
        if (txt_Paid.getText().length() != 0 && txt_Ammount.getText().length() != 0) {
            int amm = Integer.parseInt(txt_Ammount.getText().trim());
            int pa = Integer.parseInt(txt_Paid.getText().trim());
            txt_Remain.setText(amm - pa + "");
        }
    }//GEN-LAST:event_txt_RemainMouseEntered

    private void txt_PhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PhoneKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            txt_Phone.setText(txt_Phone.getText().substring(0, txt_Phone.getText().length() - 1));
        }
    }//GEN-LAST:event_txt_PhoneKeyReleased

    private void txt_AmmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AmmountKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            txt_Ammount.setText(txt_Ammount.getText().substring(0, txt_Ammount.getText().length() - 1));
        }
    }//GEN-LAST:event_txt_AmmountKeyReleased

    private void txt_PaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PaidKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            txt_Paid.setText(txt_Paid.getText().substring(0, txt_Paid.getText().length() - 1));
        }
    }//GEN-LAST:event_txt_PaidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Clear;
    private javax.swing.JButton B_add;
    private javax.swing.JButton B_exit;
    private javax.swing.JTextArea Comment_TextArea;
    private javax.swing.JSpinner Data_patient;
    private javax.swing.JTextArea Medication_txtArea;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox t1;
    private javax.swing.JCheckBox t10;
    private javax.swing.JCheckBox t11;
    private javax.swing.JCheckBox t12;
    private javax.swing.JCheckBox t13;
    private javax.swing.JCheckBox t14;
    private javax.swing.JCheckBox t15;
    private javax.swing.JCheckBox t16;
    private javax.swing.JCheckBox t17;
    private javax.swing.JCheckBox t18;
    private javax.swing.JCheckBox t19;
    private javax.swing.JCheckBox t2;
    private javax.swing.JCheckBox t20;
    private javax.swing.JCheckBox t21;
    private javax.swing.JCheckBox t22;
    private javax.swing.JCheckBox t23;
    private javax.swing.JCheckBox t24;
    private javax.swing.JCheckBox t25;
    private javax.swing.JCheckBox t26;
    private javax.swing.JCheckBox t27;
    private javax.swing.JCheckBox t28;
    private javax.swing.JCheckBox t29;
    private javax.swing.JCheckBox t3;
    private javax.swing.JCheckBox t30;
    private javax.swing.JCheckBox t31;
    private javax.swing.JCheckBox t32;
    private javax.swing.JCheckBox t4;
    private javax.swing.JCheckBox t5;
    private javax.swing.JCheckBox t6;
    private javax.swing.JCheckBox t7;
    private javax.swing.JCheckBox t8;
    private javax.swing.JCheckBox t9;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_Ammount;
    private javax.swing.JTextField txt_Paid;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_Remain;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_ln;
    // End of variables declaration//GEN-END:variables

    private boolean isFillField() {
        Boolean result = false;
        if (txt_Address.getText().length() != 0 && txt_Ammount.getText().length() != 0
                && txt_Paid.getText().length() != 0
                && txt_Phone.getText().length() != 0 && txt_Remain.getText().length() != 0
                && txt_fn.getText().length() != 0 && txt_ln.getText().length() != 0
                && Medication_txtArea.getText().length() != 0) {
            result = true;
        }
        return result;
    }
}
