/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tethproj;

import UTIL.DBHelper;
import static UTIL.DBHelper.connectDB;
import static UTIL.DBHelper.getPatientsNames;
import static UTIL.DBHelper.getPatientsPhones;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import static tethproj.Login.test;

/**
 *
 * @author SamaherD
 */
public class Search_patients extends javax.swing.JFrame {

    public static int v_id;

    /**
     * Creates new form Search
     */
    public Search_patients() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);

        nameAutoComplete();
        phoneAutoComplete();
        Teeth_frame1.setVisible(false);
        // Txt_Ammount.setEditable(false);
        //   txt_paid.setEditable(false);
        //  AR_Medical.setEditable(false);
        //      Ar_comments.setEditable(false);

    }

    // Auto complete methods
    private void nameAutoComplete() {
        ArrayList<Object> arr = getPatientsNames();
        TextAutoCompleter complete = new TextAutoCompleter(jTextField_name, arr);
    }

    private void phoneAutoComplete() {

        ArrayList<Object> arr = getPatientsPhones();
        TextAutoCompleter complete = new TextAutoCompleter(jTextField_phone, arr);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Teeth_frame = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jButton_ok = new javax.swing.JButton();
        jButton_cancel_teeth = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_id_search = new javax.swing.JLabel();
        lbl_name_search = new javax.swing.JLabel();
        lbl_phone_search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_add_search = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_total_amount_search = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_paid_amount_seatch = new javax.swing.JTextField();
        txt_remains_search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Teeth_frame1 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        B_Eidt = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        CheckBox6 = new javax.swing.JCheckBox();
        CheckBox7 = new javax.swing.JCheckBox();
        CheckBox8 = new javax.swing.JCheckBox();
        CheckBox9 = new javax.swing.JCheckBox();
        CheckBox10 = new javax.swing.JCheckBox();
        CheckBox11 = new javax.swing.JCheckBox();
        CheckBox12 = new javax.swing.JCheckBox();
        CheckBox13 = new javax.swing.JCheckBox();
        CheckBox14 = new javax.swing.JCheckBox();
        CheckBox15 = new javax.swing.JCheckBox();
        CheckBox16 = new javax.swing.JCheckBox();
        CheckBox18 = new javax.swing.JCheckBox();
        CheckBox19 = new javax.swing.JCheckBox();
        CheckBox20 = new javax.swing.JCheckBox();
        CheckBox21 = new javax.swing.JCheckBox();
        CheckBox22 = new javax.swing.JCheckBox();
        CheckBox23 = new javax.swing.JCheckBox();
        CheckBox24 = new javax.swing.JCheckBox();
        CheckBox25 = new javax.swing.JCheckBox();
        CheckBox26 = new javax.swing.JCheckBox();
        CheckBox27 = new javax.swing.JCheckBox();
        CheckBox28 = new javax.swing.JCheckBox();
        CheckBox30 = new javax.swing.JCheckBox();
        CheckBox31 = new javax.swing.JCheckBox();
        CheckBox32 = new javax.swing.JCheckBox();
        CheckBox17 = new javax.swing.JCheckBox();
        CheckBox29 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AR_Medical = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ar_comments = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Txt_Ammount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_paid = new javax.swing.JTextField();
        jButton_ok2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        Teeth_frame.setVisible(true);

        jPanel4.setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(30, 230, 90, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Teeth"));
        jPanel5.setLayout(null);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1);
        jCheckBox1.setBounds(40, 60, 21, 20);
        jPanel5.add(jCheckBox2);
        jCheckBox2.setBounds(80, 60, 20, 21);
        jPanel5.add(jCheckBox3);
        jCheckBox3.setBounds(120, 60, 20, 21);
        jPanel5.add(jCheckBox4);
        jCheckBox4.setBounds(160, 60, 20, 21);
        jPanel5.add(jCheckBox5);
        jCheckBox5.setBounds(210, 60, 20, 21);
        jPanel5.add(jCheckBox6);
        jCheckBox6.setBounds(250, 60, 20, 20);
        jPanel5.add(jCheckBox7);
        jCheckBox7.setBounds(290, 60, 21, 21);
        jPanel5.add(jCheckBox8);
        jCheckBox8.setBounds(330, 60, 20, 21);
        jPanel5.add(jCheckBox9);
        jCheckBox9.setBounds(370, 60, 21, 21);
        jPanel5.add(jCheckBox10);
        jCheckBox10.setBounds(410, 60, 20, 21);
        jPanel5.add(jCheckBox11);
        jCheckBox11.setBounds(450, 60, 20, 21);
        jPanel5.add(jCheckBox12);
        jCheckBox12.setBounds(500, 60, 20, 20);
        jPanel5.add(jCheckBox13);
        jCheckBox13.setBounds(540, 60, 20, 21);
        jPanel5.add(jCheckBox14);
        jCheckBox14.setBounds(580, 60, 20, 21);
        jPanel5.add(jCheckBox15);
        jCheckBox15.setBounds(620, 60, 20, 21);
        jPanel5.add(jCheckBox16);
        jCheckBox16.setBounds(660, 60, 20, 21);
        jPanel5.add(jCheckBox17);
        jCheckBox17.setBounds(80, 80, 20, 20);
        jPanel5.add(jCheckBox18);
        jCheckBox18.setBounds(120, 80, 21, 20);
        jPanel5.add(jCheckBox19);
        jCheckBox19.setBounds(160, 80, 21, 21);
        jPanel5.add(jCheckBox20);
        jCheckBox20.setBounds(210, 80, 20, 20);
        jPanel5.add(jCheckBox21);
        jCheckBox21.setBounds(250, 80, 21, 20);
        jPanel5.add(jCheckBox22);
        jCheckBox22.setBounds(290, 80, 21, 20);
        jPanel5.add(jCheckBox23);
        jCheckBox23.setBounds(330, 80, 20, 21);
        jPanel5.add(jCheckBox25);
        jCheckBox25.setBounds(370, 80, 21, 21);
        jPanel5.add(jCheckBox26);
        jCheckBox26.setBounds(410, 80, 20, 21);
        jPanel5.add(jCheckBox27);
        jCheckBox27.setBounds(450, 80, 20, 21);
        jPanel5.add(jCheckBox28);
        jCheckBox28.setBounds(500, 80, 20, 21);
        jPanel5.add(jCheckBox30);
        jCheckBox30.setBounds(580, 80, 20, 21);
        jPanel5.add(jCheckBox31);
        jCheckBox31.setBounds(620, 80, 21, 21);
        jPanel5.add(jCheckBox32);
        jCheckBox32.setBounds(660, 80, 20, 21);
        jPanel5.add(jCheckBox24);
        jCheckBox24.setBounds(40, 80, 20, 21);
        jPanel5.add(jCheckBox29);
        jCheckBox29.setBounds(540, 80, 20, 21);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/f.jpg"))); // NOI18N
        jPanel5.add(jLabel13);
        jLabel13.setBounds(30, 30, 666, 98);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 690, 150);

        jButton_ok.setText("Ok");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_ok);
        jButton_ok.setBounds(480, 170, 45, 23);

        jButton_cancel_teeth.setText("Cancel");
        jButton_cancel_teeth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancel_teethActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_cancel_teeth);
        jButton_cancel_teeth.setBounds(550, 170, 65, 23);

        Teeth_frame.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/البحث.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(480, 20, 220, 150);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTextField_phone.setEnabled(false);
        jTextField_phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_phoneMouseClicked(evt);
            }
        });
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyPressed(evt);
            }
        });

        jTextField_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_nameMouseClicked(evt);
            }
        });
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setText("Name");

        jLabel4.setText("Phone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 10, 470, 160);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lbl_id_search.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        lbl_id_search.setText(" ID ");

        lbl_name_search.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_name_search.setText("Patint Name");

        lbl_phone_search.setEditable(false);
        lbl_phone_search.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phone number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address");

        lbl_add_search.setEditable(false);
        lbl_add_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_add_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_add_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_add_searchKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total amount");

        txt_total_amount_search.setEditable(false);
        txt_total_amount_search.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_total_amount_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_amount_searchActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Paid amount");

        txt_paid_amount_seatch.setEditable(false);
        txt_paid_amount_seatch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        txt_remains_search.setEditable(false);
        txt_remains_search.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_remains_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remains_searchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Remains");

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel10.setText("Visits");

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Medicen", "Comments", "Amount", "Paid", "Remain"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setRowHeight(20);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(1).setPreferredWidth(80);
            table.getColumnModel().getColumn(4).setPreferredWidth(25);
            table.getColumnModel().getColumn(5).setPreferredWidth(25);
            table.getColumnModel().getColumn(6).setPreferredWidth(25);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbl_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lbl_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_phone_search, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_total_amount_search, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_paid_amount_seatch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_remains_search, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_add_search, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phone_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_add_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_amount_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_paid_amount_seatch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remains_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 170, 700, 460);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(480, 630, 55, 30);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(550, 630, 70, 30);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-10, -10, 750, 680);

        Teeth_frame1.setVisible(true);

        jPanel6.setLayout(null);

        B_Eidt.setText("Ok");
        B_Eidt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_EidtMouseClicked(evt);
            }
        });
        B_Eidt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EidtActionPerformed(evt);
            }
        });
        jPanel6.add(B_Eidt);
        B_Eidt.setBounds(590, 490, 110, 20);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Teeth"));
        jPanel7.setLayout(null);

        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(CheckBox1);
        CheckBox1.setBounds(660, 60, 21, 20);
        jPanel7.add(CheckBox2);
        CheckBox2.setBounds(620, 60, 20, 21);
        jPanel7.add(CheckBox3);
        CheckBox3.setBounds(580, 60, 20, 21);
        jPanel7.add(CheckBox4);
        CheckBox4.setBounds(540, 60, 20, 21);
        jPanel7.add(CheckBox5);
        CheckBox5.setBounds(500, 60, 20, 21);
        jPanel7.add(CheckBox6);
        CheckBox6.setBounds(450, 60, 20, 20);
        jPanel7.add(CheckBox7);
        CheckBox7.setBounds(410, 60, 21, 21);
        jPanel7.add(CheckBox8);
        CheckBox8.setBounds(370, 60, 20, 21);
        jPanel7.add(CheckBox9);
        CheckBox9.setBounds(330, 60, 21, 21);
        jPanel7.add(CheckBox10);
        CheckBox10.setBounds(290, 60, 20, 21);
        jPanel7.add(CheckBox11);
        CheckBox11.setBounds(250, 60, 20, 21);
        jPanel7.add(CheckBox12);
        CheckBox12.setBounds(210, 60, 20, 20);
        jPanel7.add(CheckBox13);
        CheckBox13.setBounds(160, 60, 20, 21);
        jPanel7.add(CheckBox14);
        CheckBox14.setBounds(120, 60, 20, 21);
        jPanel7.add(CheckBox15);
        CheckBox15.setBounds(80, 60, 20, 21);
        jPanel7.add(CheckBox16);
        CheckBox16.setBounds(40, 60, 20, 21);
        jPanel7.add(CheckBox18);
        CheckBox18.setBounds(620, 80, 20, 20);
        jPanel7.add(CheckBox19);
        CheckBox19.setBounds(580, 80, 21, 20);
        jPanel7.add(CheckBox20);
        CheckBox20.setBounds(540, 80, 21, 21);
        jPanel7.add(CheckBox21);
        CheckBox21.setBounds(500, 80, 20, 20);
        jPanel7.add(CheckBox22);
        CheckBox22.setBounds(450, 80, 21, 20);
        jPanel7.add(CheckBox23);
        CheckBox23.setBounds(410, 80, 21, 20);
        jPanel7.add(CheckBox24);
        CheckBox24.setBounds(370, 80, 20, 21);
        jPanel7.add(CheckBox25);
        CheckBox25.setBounds(330, 80, 21, 21);
        jPanel7.add(CheckBox26);
        CheckBox26.setBounds(290, 80, 20, 21);
        jPanel7.add(CheckBox27);
        CheckBox27.setBounds(250, 80, 20, 21);
        jPanel7.add(CheckBox28);
        CheckBox28.setBounds(210, 80, 20, 21);
        jPanel7.add(CheckBox30);
        CheckBox30.setBounds(120, 80, 20, 21);
        jPanel7.add(CheckBox31);
        CheckBox31.setBounds(80, 80, 21, 21);
        jPanel7.add(CheckBox32);
        CheckBox32.setBounds(40, 80, 20, 21);
        jPanel7.add(CheckBox17);
        CheckBox17.setBounds(660, 80, 20, 21);
        jPanel7.add(CheckBox29);
        CheckBox29.setBounds(160, 80, 20, 21);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/f.jpg"))); // NOI18N
        jPanel7.add(jLabel14);
        jLabel14.setBounds(30, 38, 666, 100);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 710, 150);

        AR_Medical.setColumns(20);
        AR_Medical.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        AR_Medical.setRows(5);
        jScrollPane2.setViewportView(AR_Medical);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(20, 186, 680, 80);

        Ar_comments.setColumns(20);
        Ar_comments.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Ar_comments.setForeground(new java.awt.Color(255, 0, 0));
        Ar_comments.setRows(5);
        jScrollPane3.setViewportView(Ar_comments);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(20, 300, 680, 60);

        jLabel7.setText("Medical");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(30, 154, 60, 20);

        jLabel15.setText("Comments : ");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(30, 280, 70, 14);
        jPanel6.add(Txt_Ammount);
        Txt_Ammount.setBounds(20, 400, 130, 30);

        jLabel16.setText("Amount :");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(30, 370, 60, 20);

        jLabel17.setText("Paid :");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(30, 430, 60, 20);
        jPanel6.add(txt_paid);
        txt_paid.setBounds(20, 460, 130, 30);

        jButton_ok2.setText("Edit");
        jButton_ok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ok2MouseClicked(evt);
            }
        });
        jButton_ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ok2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_ok2);
        jButton_ok2.setBounds(460, 490, 110, 20);

        Teeth_frame1.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Teeth_frame1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Teeth_frame1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controlPanel i = new controlPanel();
        i.setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_phoneMouseClicked
        // TODO add your handling code here:
        jTextField_name.setText("");
        jTextField_name.setEnabled(false);
        jTextField_phone.setEnabled(true);

    }//GEN-LAST:event_jTextField_phoneMouseClicked

    private void jTextField_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nameMouseClicked
        // TODO add your handling code here:
        jTextField_phone.setText("");
        jTextField_phone.setEnabled(false);
        jTextField_name.setEnabled(true);
    }//GEN-LAST:event_jTextField_nameMouseClicked

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            HashMap result = DBHelper.getPatientInformation(1, (jTextField_name.getText()).trim());
            try {
                fillData(result);
            } catch (SQLException ex) {
                Logger.getLogger(Search_patients.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jTextField_nameKeyPressed
    }

    private void txt_total_amount_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_amount_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_amount_searchActionPerformed

    private void txt_remains_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remains_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remains_searchActionPerformed

    private void jTextField_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            HashMap result = DBHelper.getPatientInformation(2, (jTextField_phone.getText()).trim());
            try {
                fillData(result);
            } catch (SQLException ex) {
                Logger.getLogger(Search_patients.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTextField_phoneKeyPressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            Teeth_frame1.setVisible(true);

            int row = table.getSelectedRow();
            v_id = (int) table.getValueAt(row, 0);
            table.setBackground(Color.red);

            Connection conn = connectDB();

            String sss = "SELECT teeth  FROM visits WHERE "
                    + "(visit_id= '" + v_id + "' and pacient_id = ?)";
            PreparedStatement ppp = conn.prepareStatement(sss);
            ppp.setString(1, lbl_id_search.getText().trim());

            ResultSet rrr = ppp.executeQuery();

            if (rrr.next()) {
                String s1 = rrr.getString("teeth").trim();
                ArrayList<Integer> ans = new ArrayList<>();

                StringTokenizer stt = new StringTokenizer(s1, " ");

                while (stt.hasMoreTokens()) {
                    String token = stt.nextToken();

                    ans.add(Integer.parseInt(token));

                }
                Boolean[] answer = new Boolean[33];
                for (int i = 0; i <= 32; i++) {
                    answer[i] = false;
                }

                for (Integer an : ans) {
                    answer[an] = true;
                }

                CheckBox1.setSelected(answer[0]);
                CheckBox2.setSelected(answer[1]);
                CheckBox3.setSelected(answer[2]);
                CheckBox4.setSelected(answer[3]);
                CheckBox5.setSelected(answer[4]);
                CheckBox6.setSelected(answer[5]);
                CheckBox7.setSelected(answer[6]);
                CheckBox8.setSelected(answer[7]);
                CheckBox9.setSelected(answer[8]);
                CheckBox10.setSelected(answer[9]);
                CheckBox11.setSelected(answer[10]);
                CheckBox12.setSelected(answer[11]);
                CheckBox13.setSelected(answer[12]);
                CheckBox14.setSelected(answer[13]);
                CheckBox15.setSelected(answer[14]);
                CheckBox16.setSelected(answer[15]);
                CheckBox17.setSelected(answer[16]);
                CheckBox18.setSelected(answer[17]);
                CheckBox19.setSelected(answer[18]);
                CheckBox20.setSelected(answer[19]);
                CheckBox21.setSelected(answer[20]);
                CheckBox22.setSelected(answer[21]);
                CheckBox23.setSelected(answer[22]);
                CheckBox24.setSelected(answer[23]);
                CheckBox25.setSelected(answer[24]);
                CheckBox26.setSelected(answer[25]);
                CheckBox27.setSelected(answer[26]);
                CheckBox28.setSelected(answer[27]);
                CheckBox29.setSelected(answer[28]);
                CheckBox30.setSelected(answer[29]);
                CheckBox31.setSelected(answer[30]);
                CheckBox32.setSelected(answer[31]);

            }
            String test = "SELECT medicen,comments,amount,paid FROM visits WHERE "
                    + "(visit_id= '" + v_id + "' and pacient_id = ?)";
            PreparedStatement p = conn.prepareStatement(test);
            p.setString(1, lbl_id_search.getText().trim());

            ResultSet r = p.executeQuery();
            if (r.next()) {
                AR_Medical.setText(r.getString("medicen"));
                Ar_comments.setText(r.getString("comments"));
                Txt_Ammount.setText(r.getString("amount"));
                txt_paid.setText(r.getString("paid"));
            }
        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_tableMouseClicked

    private void jButton_cancel_teethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancel_teethActionPerformed

    }//GEN-LAST:event_jButton_cancel_teethActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed


    }//GEN-LAST:event_jButton_okActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_EidtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EidtActionPerformed
        CheckBox1.setSelected(false);
        CheckBox2.setSelected(false);
        CheckBox3.setSelected(false);
        CheckBox4.setSelected(false);
        CheckBox5.setSelected(false);
        CheckBox6.setSelected(false);
        CheckBox7.setSelected(false);
        CheckBox8.setSelected(false);
        CheckBox9.setSelected(false);
        CheckBox10.setSelected(false);
        CheckBox11.setSelected(false);
        CheckBox12.setSelected(false);
        CheckBox13.setSelected(false);
        CheckBox14.setSelected(false);
        CheckBox15.setSelected(false);
        CheckBox16.setSelected(false);
        CheckBox17.setSelected(false);
        CheckBox18.setSelected(false);
        CheckBox19.setSelected(false);
        CheckBox20.setSelected(false);
        CheckBox21.setSelected(false);
        CheckBox22.setSelected(false);
        CheckBox23.setSelected(false);
        CheckBox24.setSelected(false);
        CheckBox25.setSelected(false);
        CheckBox26.setSelected(false);
        CheckBox27.setSelected(false);
        CheckBox28.setSelected(false);
        CheckBox29.setSelected(false);
        CheckBox30.setSelected(false);
        CheckBox31.setSelected(false);
        CheckBox32.setSelected(false);
        Teeth_frame1.setVisible(false);

    }//GEN-LAST:event_B_EidtActionPerformed

    private void B_EidtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EidtMouseClicked

    }//GEN-LAST:event_B_EidtMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (test) {
            controlPanel c = new controlPanel();
            c.show();
            this.hide();
        } else {
            Login l = new Login();
            l.show();
            this.hide();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbl_add_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_add_searchKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            lbl_add_search.setText(lbl_add_search.getText().substring(0, lbl_add_search.getText().length() - 1));
        }
    }//GEN-LAST:event_lbl_add_searchKeyReleased

    private void lbl_add_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_add_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            lbl_add_search.setText(lbl_add_search.getText().substring(0, lbl_add_search.getText().length() - 1));
        }
    }//GEN-LAST:event_lbl_add_searchKeyPressed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void jButton_ok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ok2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ok2MouseClicked

    private void jButton_ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ok2ActionPerformed
        // TODO add your handling code here:
        //Here The modif shit :3 
        //    txt_paid.setEditable(true);
        //    Txt_Ammount.setEditable(true);
        //    Ar_comments.setEditable(true);
        //     AR_Medical.setEditable(true);
        try {
            Connection conn = connectDB();
            String s = "Update visits Set medicen=?,comments=?,amount=?,paid=? WHERE (visit_id= '" + v_id + "' and pacient_id = ?)";
            PreparedStatement p;

            p = conn.prepareStatement(s);
            p.setString(1, AR_Medical.getText().trim());
            p.setString(2, Ar_comments.getText().trim());
            p.setString(3, Txt_Ammount.getText().trim());
            p.setString(4, txt_paid.getText().trim());
            p.setString(5, lbl_id_search.getText().trim());
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Edited Sucssfully");
        } catch (SQLException ex) {
            Logger.getLogger(Search_patients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_ok2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_patients().setVisible(true);
            }
        });
    }

    private void fillData(HashMap result) throws SQLException {

        lbl_id_search.setText((String) result.get("id"));
        lbl_name_search.setText((String) result.get("name"));
        lbl_phone_search.setText((String) result.get("phone"));
        lbl_add_search.setText((String) result.get("address"));
        lbl_error.setText((String) result.get("msg"));
        lbl_error.setForeground((Color) result.get("Foreground"));
        txt_total_amount_search.setText((String) result.get("totalAmount"));
        txt_paid_amount_seatch.setText((String) result.get("paidAmount"));
        txt_remains_search.setText((String) result.get("remaind"));

        if (result.get("haseTableData").equals(true)) {

            table.setModel(UTIL.BuildModel.buildTableModel((ResultSet) result.get("tableData"), table));
            DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
            headerRenderer.setBackground(new Color(92, 81, 80));
            headerRenderer.setForeground(Color.WHITE);

            for (int i = 0; i < table.getModel().getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            }
            table.setIntercellSpacing(new Dimension(0, 0));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AR_Medical;
    private javax.swing.JTextArea Ar_comments;
    private javax.swing.JButton B_Eidt;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox10;
    private javax.swing.JCheckBox CheckBox11;
    private javax.swing.JCheckBox CheckBox12;
    private javax.swing.JCheckBox CheckBox13;
    private javax.swing.JCheckBox CheckBox14;
    private javax.swing.JCheckBox CheckBox15;
    private javax.swing.JCheckBox CheckBox16;
    private javax.swing.JCheckBox CheckBox17;
    private javax.swing.JCheckBox CheckBox18;
    private javax.swing.JCheckBox CheckBox19;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox20;
    private javax.swing.JCheckBox CheckBox21;
    private javax.swing.JCheckBox CheckBox22;
    private javax.swing.JCheckBox CheckBox23;
    private javax.swing.JCheckBox CheckBox24;
    private javax.swing.JCheckBox CheckBox25;
    private javax.swing.JCheckBox CheckBox26;
    private javax.swing.JCheckBox CheckBox27;
    private javax.swing.JCheckBox CheckBox28;
    private javax.swing.JCheckBox CheckBox29;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox30;
    private javax.swing.JCheckBox CheckBox31;
    private javax.swing.JCheckBox CheckBox32;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JCheckBox CheckBox6;
    private javax.swing.JCheckBox CheckBox7;
    private javax.swing.JCheckBox CheckBox8;
    private javax.swing.JCheckBox CheckBox9;
    private javax.swing.JInternalFrame Teeth_frame;
    private javax.swing.JInternalFrame Teeth_frame1;
    private javax.swing.JTextField Txt_Ammount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_cancel_teeth;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JButton jButton_ok2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lbl_add_search;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_id_search;
    private javax.swing.JLabel lbl_name_search;
    private javax.swing.JTextField lbl_phone_search;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_paid;
    private javax.swing.JTextField txt_paid_amount_seatch;
    private javax.swing.JTextField txt_remains_search;
    private javax.swing.JTextField txt_total_amount_search;
    // End of variables declaration//GEN-END:variables
}
